// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testgroupbox.proxies;

public class TestContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TestGroupBox.TestContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ShowGroupBox1("ShowGroupBox1"),
		ShowGroupBox2("ShowGroupBox2"),
		ShowGroupBox3("ShowGroupBox3");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testContextMendixObject)
	{
		if (testContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, testContextMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testContextMendixObject = testContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static testgroupbox.proxies.TestContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new testgroupbox.proxies.TestContext(context, mendixObject);
	}

	public static testgroupbox.proxies.TestContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return testgroupbox.proxies.TestContext.initialize(context, mendixObject);
	}

	/**
	 * @return value of ShowGroupBox1
	 */
	public final java.lang.Boolean getShowGroupBox1()
	{
		return getShowGroupBox1(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowGroupBox1
	 */
	public final java.lang.Boolean getShowGroupBox1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowGroupBox1.toString());
	}

	/**
	 * Set value of ShowGroupBox1
	 * @param showgroupbox1
	 */
	public final void setShowGroupBox1(java.lang.Boolean showgroupbox1)
	{
		setShowGroupBox1(getContext(), showgroupbox1);
	}

	/**
	 * Set value of ShowGroupBox1
	 * @param context
	 * @param showgroupbox1
	 */
	public final void setShowGroupBox1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showgroupbox1)
	{
		getMendixObject().setValue(context, MemberNames.ShowGroupBox1.toString(), showgroupbox1);
	}

	/**
	 * @return value of ShowGroupBox2
	 */
	public final java.lang.Boolean getShowGroupBox2()
	{
		return getShowGroupBox2(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowGroupBox2
	 */
	public final java.lang.Boolean getShowGroupBox2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowGroupBox2.toString());
	}

	/**
	 * Set value of ShowGroupBox2
	 * @param showgroupbox2
	 */
	public final void setShowGroupBox2(java.lang.Boolean showgroupbox2)
	{
		setShowGroupBox2(getContext(), showgroupbox2);
	}

	/**
	 * Set value of ShowGroupBox2
	 * @param context
	 * @param showgroupbox2
	 */
	public final void setShowGroupBox2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showgroupbox2)
	{
		getMendixObject().setValue(context, MemberNames.ShowGroupBox2.toString(), showgroupbox2);
	}

	/**
	 * @return value of ShowGroupBox3
	 */
	public final java.lang.Boolean getShowGroupBox3()
	{
		return getShowGroupBox3(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowGroupBox3
	 */
	public final java.lang.Boolean getShowGroupBox3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowGroupBox3.toString());
	}

	/**
	 * Set value of ShowGroupBox3
	 * @param showgroupbox3
	 */
	public final void setShowGroupBox3(java.lang.Boolean showgroupbox3)
	{
		setShowGroupBox3(getContext(), showgroupbox3);
	}

	/**
	 * Set value of ShowGroupBox3
	 * @param context
	 * @param showgroupbox3
	 */
	public final void setShowGroupBox3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showgroupbox3)
	{
		getMendixObject().setValue(context, MemberNames.ShowGroupBox3.toString(), showgroupbox3);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final testgroupbox.proxies.TestContext that = (testgroupbox.proxies.TestContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
