// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testgroupbox.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the TestGroupBox module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TestContextAttr_OpenPageBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TestGroupBox.ACT_TestContextAttr_OpenPage");
		return builder;
	}

	public static void aCT_TestContextAttr_OpenPage(IContext context)
	{
		aCT_TestContextAttr_OpenPageBuilder().execute(context);
	}
}
