// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum Enum_DistanceUnit
{
	KILOMETER("47de330e-5db4-41bc-8954-72dd45215dca"),
	STATUTE_MILE("f6789c80-5ab3-4b27-b7e1-a2e6d63eaa79"),
	NAUTICAL_MILE("5960bf28-4a15-4e59-b3ce-e30205031ae5");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_DistanceUnit(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
