// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("cc22125c-c1f0-43e2-90af-d6c9ca9ebe9d"),
	startsWith("b9c93428-af6d-4067-9bf0-34752cc23ed0"),
	endsWith("6d538a25-2bb8-4010-9f71-3f4662801a53"),
	between("a8aad510-3b9a-4406-be59-abbfdbd494a1"),
	greater("b0267d81-44cf-4d4a-a426-681aa9be1eb8"),
	greaterEqual("f09f126b-d58b-4923-9d24-a7463035ef8b"),
	equal("ef14844f-62ba-46bc-91e9-0ecf03f63a8d"),
	notEqual("324ccea7-80e2-4511-aff6-29e4997d6116"),
	smaller("cf7ef76e-beca-4ce4-9c61-f5ae8e38ad22"),
	smallerEqual("89d60237-5451-4752-b206-bfd9be28473b"),
	empty("8ca50d48-0d6e-469b-adf0-24a35e57ea0c"),
	notEmpty("c4a1d84f-2e63-4b85-96a1-8675cfcb64d3");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
