// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("fc230d65-c6a7-45fb-a4a4-a12381ad6d36"),
	startsWith("99c31847-e4d5-45d8-a9b7-94aae2e13574"),
	endsWith("1f739292-5bea-4aa7-a140-a4052d66c728"),
	between("1ec4a69c-03af-4331-92fb-d761a7507740"),
	greater("bb0e0f21-b12b-469a-a523-1e56369293ce"),
	greaterEqual("efa9dd7a-9d0d-4446-be7a-f2b54bcaf4cf"),
	equal("965c6bd1-3ec6-4dd2-9e72-3b47ec918184"),
	notEqual("427241d1-38bd-405b-9b79-b4d0f2a60e3c"),
	smaller("ccfa39b6-b6ea-425a-8980-69a68976a1d8"),
	smallerEqual("4289d052-9a85-44df-bf9b-99694cdda98d"),
	empty("642c8d2d-783e-4d28-a5d8-d2af0cc4ed38"),
	notEmpty("9fe2fa22-59b2-4077-8844-c6c9cba7ecd1");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
