// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("ca8e8b45-2b73-42a8-b705-cfa4b12c221a"),
	startsWith("726ce730-bd52-4699-8558-98fafd2863f5"),
	endsWith("dd491b82-be65-4369-ae16-ad1d15fa0bc1"),
	between("7cc97ce1-ac4c-43f7-b72f-84ad2c5d0ea0"),
	greater("1b071603-189d-4c13-8428-40b2433e121b"),
	greaterEqual("91912871-cd84-4520-8d1a-cf78f7a8ded2"),
	equal("7623adf4-d687-440b-928f-78f683378768"),
	notEqual("f43575db-6b40-429f-b685-47b7e73d2856"),
	smaller("d947f41d-b0aa-400b-9267-9c4bb4a1275e"),
	smallerEqual("9b4cbd27-0fed-406c-9931-647ac69fdcc6"),
	empty("c5e4f0cb-5092-4f5d-89f7-69893ea1fdf1"),
	notEmpty("52ae6395-0815-4d10-8b37-be02a57fcd28");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
